[project]
name = "llm-biodomain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fire>=0.7.0",
    "obonet>=1.1.1",
    "polars>=1.30.0",
    "ranx>=0.3.20",
]